Repository SBNSoftware/icaruscode, pull requests merged in 2023-01, with the labels that each got.

#503 Trigger decoder tool supporting both V2 and V3 data fragment versions [SBN2022B]
  fcl/reco/Definitions/decoderdefs_icarus.fcl
  fcl/reco/Definitions/stage0_icarus_defs.fcl
  fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
  icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
  icaruscode/Decode/DataProducts/TriggerConfiguration.cxx
  icaruscode/Decode/DataProducts/TriggerConfiguration.h
  icaruscode/Decode/DataProducts/classes_def.xml
  icaruscode/Decode/DecoderTools/CMakeLists.txt
  icaruscode/Decode/DecoderTools/IDecoder.h
  icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
  icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.h
  icaruscode/Decode/DecoderTools/TriggerDecoderDispatcher_tool.cc
  icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
  icaruscode/Decode/TriggerConfigurationExtraction_module.cc
Labels: enhancement

#513 GENIE event generator list set back to Default
  fcl/gen/genie/genie_icarus_bnb.fcl
Labels: maintenance

#502 Trigger decoder tool supporting both V2 and V3 data fragment versions
  fcl/reco/Definitions/decoderdefs_icarus.fcl
  fcl/reco/Definitions/stage0_icarus_defs.fcl
  fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
  icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
  icaruscode/Decode/DataProducts/TriggerConfiguration.cxx
  icaruscode/Decode/DataProducts/TriggerConfiguration.h
  icaruscode/Decode/DataProducts/classes_def.xml
  icaruscode/Decode/DecoderTools/CMakeLists.txt
  icaruscode/Decode/DecoderTools/IDecoder.h
  icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
  icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.h
  icaruscode/Decode/DecoderTools/TriggerDecoderDispatcher_tool.cc
  icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
  icaruscode/Decode/TriggerConfigurationExtraction_module.cc
Labels: enhancement

#424 Feature/rh all pf os for dev
  fcl/caf/cafmaker_defs.fcl
  fcl/reco/Definitions/stage1_icarus_defs.fcl
  icaruscode/Decode/fcl/deprecated/stage1_icarus_defs.fcl
Labels: breaking

#491 Trigger simulation in production workflow
  fcl/configurations/beamgates_icarus.fcl
  fcl/gen/MultiVertex/multivertex_icarus.fcl
  fcl/gen/background/prodbackground_Ar39_icarus.fcl
  fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
  fcl/gen/corsika/prodcorsika_proton_intime_icarus_numi.fcl
  fcl/gen/corsika/prodcorsika_standard_icarus.fcl
  fcl/gen/genie/prodcorsika_genie_standard_icarus.fcl
  fcl/gen/genie/simulation_genie_icarus_bnb.fcl
  fcl/gen/genie/simulation_genie_icarus_simple.fcl
  fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
  fcl/gen/mevprtl/hnl/hnl_icarus_gen.fcl
  fcl/gen/numi/simulation_genie_icarus_numi.fcl
  fcl/gen/numi/simulation_numi.fcl
  fcl/gen/numi/simulation_numi_nue.fcl
  fcl/gen/numi/simulation_numi_numu.fcl
  fcl/gen/overlay/prodoverlay_proton_sbnflux_icarus.fcl
  fcl/gen/single/prodsingle_common_icarus.fcl
  fcl/gen/text/prodtext_standard_icarus.fcl
  fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
  icaruscode/PMT/Trigger/simulate_triggers_icarus.fcl
  icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
  icaruscode/PMT/Trigger/trigger_icarus.fcl
Labels: enhancement, new CI ref

#498 PMT readout simulation
  icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
  icaruscode/IcarusObj/OpDetWaveformMeta.h
  icaruscode/PMT/Algorithms/ConstantPedestalGeneratorAlg.h
  icaruscode/PMT/Algorithms/DiscretePhotoelectronPulse.cxx
  icaruscode/PMT/Algorithms/FastGaussianNoiseGeneratorAlg.h
  icaruscode/PMT/Algorithms/GaussianNoiseGeneratorAlg.h
  icaruscode/PMT/Algorithms/NoNoiseGeneratorAlg.h
  icaruscode/PMT/Algorithms/NoiseGeneratorAlg.h
  icaruscode/PMT/Algorithms/PMTReadoutWindowMaker.h
  icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
  icaruscode/PMT/Algorithms/PMTsimulationAlg.h
  icaruscode/PMT/Algorithms/PedestalGeneratorAlg.h
  icaruscode/PMT/Algorithms/PhotoelectronPulseFunction.h
  icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
  icaruscode/PMT/CMakeLists.txt
  icaruscode/PMT/PMTconstantPedestalGeneratorTool_tool.cc
  icaruscode/PMT/PMTfastGausNoiseGeneratorTool_tool.cc
  icaruscode/PMT/PMTgausNoiseGeneratorTool_tool.cc
  icaruscode/PMT/PMTnoNoiseGeneratorTool_tool.cc
  icaruscode/PMT/PMTnoiseGeneratorTool.h
  icaruscode/PMT/PMTnoiseGeneratorToolBase.h
  icaruscode/PMT/PMTpedestalGeneratorTool.h
  icaruscode/PMT/PMTpedestalGeneratorToolBase.h
  icaruscode/PMT/SimPMTIcarus_module.cc
  icaruscode/PMT/SimPMTreadout_module.cc
  icaruscode/PMT/Trigger/Algorithms/SlidingWindowPatternAlg.cxx
  icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.cxx
  icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.h
  icaruscode/PMT/Trigger/Algorithms/WindowTopologyAlg.cxx
  icaruscode/PMT/Trigger/SlidingWindowTriggerSimulation_module.cc
  icaruscode/PMT/Trigger/TriggerSimulationOnGates_module.cc
  icaruscode/PMT/Trigger/simulate_trigger_primitives_icarus.fcl
  icaruscode/PMT/Trigger/simulate_triggers_icarus.fcl
  icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
  icaruscode/PMT/Trigger/trigger_icarus.fcl
  icaruscode/PMT/run_pmtreadoutsimulation_icarus.fcl
  icaruscode/Utilities/DetectorClocksHelpers.h
  icaruscode/Utilities/intervals_utils.h
  icaruscode/Utilities/quantities_utils.h
Labels: enhancement
