Repository SBNSoftware/icaruscode, pull requests merged in 2023-04, with the labels that each got.

#561 CAFmaker w/o event weights for detsim2d
  fcl/caf/cafmaker_add_detsim2d_icarus.fcl
  fcl/caf/cafmakerjob_icarus_detsim2d.fcl
  fcl/caf/cafmakerjob_icarus_detsim2d_systtools_and_fluxwgt.fcl
Labels: breaking

#554 PMT digitization does not truncate large signals any more.
  icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
  icaruscode/PMT/Algorithms/PMTsimulationAlg.h
  icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
Labels: bug, enhancement, breaking

#563 `prodtext_standard_icarus.fcl`: add mandatory parameter
  fcl/gen/text/prodtext_standard_icarus.fcl
Labels: bug

#568 Fix a bug in PMT digitization
  icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
Labels: bug

#569 Fix a bug in PMT digitization [`develop`]
  icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
Labels: bug
