Repository SBNSoftware/icaruscode, pull requests merged in 2024-04, with the labels that each got.

#728 Set dropped MCParticle label properly
  fcl/g4/intime_g4_icarus.fcl
  fcl/g4/larg4_icarus.fcl
  fcl/g4/standard_g4_icarus.fcl
Labels: bug

#722 Script maintenance
  scripts/generateOverburdenConfigurations.sh
  scripts/makeNoOverburdenVersionOf.sh
  scripts/makeOverburdenVersionOf.sh
  scripts/manageDataRunDefinitions.py
  scripts/runFilesFromSAM.py
  scripts/runFilesFromSAM.sh
  scripts/sortDataLoggerFiles.py
Labels: enhancement, maintenance

#723 Added trigger logic information to PMT decoder diagnostic ROOT tree
  fcl/reco/Stage0/Run2/partial/decodePMT_icarus_treeonly.fcl
  icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
Labels: maintenance

#724 rootoutput_icarus.fcl: added icarus_rootoutput_one_output_per_input
  fcl/configurations/rootoutput_icarus.fcl
Labels: enhancement

#725 Update PostGres DB new column names
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx
Labels: bug, maintenance

#726 add simplemerge
  fcl/g4/larg4_icarus.fcl
  fcl/g4/simplemerge_icarus.fcl
Labels: enhancement
