Repository SBNSoftware/icaruscode, pull requests merged in 2024-10, with the labels that each got.

#732 Update for PMT gain calibration tools
  icaruscode/PMT/Calibration/CMakeLists.txt
  icaruscode/PMT/Calibration/CaloTools/CMakeLists.txt
  icaruscode/PMT/Calibration/CaloTools/FitBackgroundPhotons.cc
  icaruscode/PMT/Calibration/CaloTools/FitBackgroundPhotons.h
  icaruscode/PMT/Calibration/CaloTools/IdealPmtResponse.h
  icaruscode/PMT/Calibration/CaloTools/SPEChargeIdealResponse.h
  icaruscode/PMT/Calibration/CaloTools/SPEChargeLogisticResponse.h
  icaruscode/PMT/Calibration/CaloTools/SPEChargeResponse.h
  icaruscode/PMT/Calibration/PMTBackgroundphotonsCalibration_module.cc
  icaruscode/PMT/Calibration/fcl/CMakeLists.txt
  icaruscode/PMT/Calibration/fcl/bkgphotons-calibration.fcl
  icaruscode/PMT/Calibration/fcl/bkgphotons-calibration_v3.fcl
  icaruscode/PMT/Calibration/fcl/pmt-calibration.fcl
  icaruscode/PMT/Calibration/fitPulseDistribution.cc
  icaruscode/PMT/Calibration/fitPulseDistribution.cc.1
Labels: enhancement

#751 Beam timing integration and optical calibration nutples update
  fcl/reco/Definitions/stage0_icarus_defs.fcl
  fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
  icaruscode/IcarusObj/PMTBeamSignal.h
  icaruscode/PMT/OpReco/CMakeLists.txt
  icaruscode/PMT/OpReco/ICARUSBeamStructureAna_module.cc
  icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
  icaruscode/PMT/OpReco/driver/run_beamstructure_ana.fcl
  icaruscode/PMT/OpReco/driver/run_flashana.fcl
  icaruscode/PMT/OpReco/fcl/icarus_opana_modules.fcl
  icaruscode/Timing/CMakeLists.txt
  icaruscode/Timing/PMTBeamSignalsExtractor_module.cc
  icaruscode/Timing/timing_beam.fcl
Labels: enhancement

#757 Remove unused TTTResetDelay, improve documentation
  icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
Labels: documentation, maintenance

#758 Run-time bug fixes for PR#751
  icaruscode/IcarusObj/classes.h
  icaruscode/IcarusObj/classes_def.xml
  icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
  icaruscode/PMT/OpReco/fcl/icarus_opana_modules.fcl
Labels: bug

#760 Bug fix to CRT PMT Matching producer
  icaruscode/CRT/CRTPMTMatchingAna_module.cc
  icaruscode/CRT/CRTPMTMatchingProducer_module.cc
  icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
Labels: bug

#749 Fixes from Clang compilation errors
  icaruscode/Decode/ChannelMapping/Legacy/ChannelMapPostGres_tool.cc
  icaruscode/Decode/ChannelMapping/Legacy/ChannelMapSQLite_tool.cc
  icaruscode/PMT/Algorithms/ParsingToolkit.h
  icaruscode/PMT/Calibration/CaloTools/SPEChargeLogisticResponse.h
  icaruscode/PMT/OpReco/ICARUSBeamStructureAna_module.cc
  icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
  icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
Labels: maintenance

#770 This fixed a CRTPMTMatchingProducer bug.
  icaruscode/CRT/CRTPMTMatchingAna_module.cc
  icaruscode/CRT/CRTPMTMatchingProducer_module.cc
  icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
Labels: bug

#771 Update detector variation fcl files to fix bug in induction 1 gain value and clean up for BNB analysis
  fcl/syst_variations/caf_variations_saveAR_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_cohm1_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_cohm2_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_cohp1_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_cohp2_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_intm1_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_intnoise0p9_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_intnoise1p1_icarus.fcl
  fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_intp1_icarus.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_light_variations.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_untuned_variations.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_ind0gainhi.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_ind0gainlow.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_ind1_opaque.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_ind1_transparent.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_run2lifetimehi.fcl
  fcl/syst_variations/detsim_2d_icarus_refactored_variation_run2lifetimelow.fcl
  fcl/syst_variations/detsim_2d_variation_fitFR_refactored_icarus.fcl
  fcl/syst_variations/detsim_2d_variation_refactored_icarus.fcl
  fcl/syst_variations/nuonly_sample_gen.fcl
  fcl/syst_variations/run_icarusMC_supera.fcl
  fcl/syst_variations/scrub_stage1_qechange_variations_icarus.fcl
  fcl/syst_variations/scrub_stage1_variations_icarus.fcl
  fcl/syst_variations/stage0_variation_icarus_savewires.fcl
  fcl/syst_variations/stage1_variation_icarus.fcl
  fcl/syst_variations/stage1_variation_icarus_saveallcalibtracks.fcl
Labels: enhancement
