Repository SBNSoftware/icaruscode, pull requests merged in 2024-03, with the labels that each got.

#696 Update TPC Channel Status database tags to v3r2
  fcl/configurations/calibration_database_GlobalTags_icarus.fcl
  fcl/configurations/calibration_database_TPC_TagSets_icarus.fcl
Labels: maintenance

#697 Moveing SystTools from icaruscode to sbncode
  fcl/caf/CMakeLists.txt
  fcl/caf/SystTools/CMakeLists.txt
  fcl/caf/SystTools/configs/CMakeLists.txt
  fcl/caf/SystTools/configs/config_All_icarus_v2.fcl
  fcl/caf/SystTools/configs/config_GENIEReWeightMultisigma_icarus_v2.fcl
  fcl/caf/SystTools/configs/config_GENIEReWeightMultisim_icarus_v2.fcl
  fcl/caf/SystTools/configs/config_MINERvA_E2p2h_icarus_v1.fcl
  fcl/caf/SystTools/configs/config_MINERvAq0q3Tune_icarus_v1.fcl
  fcl/caf/SystTools/configs/config_MiscInteractionSysts_icarus_v1.fcl
  fcl/caf/SystTools/configs/config_NOvAStyleNonResPion_icarus_v1.fcl
  fcl/caf/SystTools/eventweight_genie_systtools.fcl
  fcl/caf/SystTools/syst_params_icarus_v2.fcl
  fcl/caf/cafmakerjob_icarus_detsim2d_systtools.fcl
  fcl/caf/cafmakerjob_icarus_systtools.fcl
Labels: maintenance

#699 Use run number for TPC calibration
  icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
  icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
  icaruscode/TPC/Calorimetry/normtools_icarus.fcl
Labels: enhancement

#675 Update the drift velocity in the WireCell simparams.jsonnet
  icaruscode/TPC/ICARUSWireCell/icarus/simparams.jsonnet
Labels: maintenance

#709 Channel mapping interface change
  fcl/reco/Definitions/CAEN_V1730_setup_icarus.fcl
  icaruscode/CRT/CRTUtils/CRTHitRecoAlg.h
  icaruscode/Decode/ChannelMapping/CMakeLists.txt
  icaruscode/Decode/ChannelMapping/ChannelMapDumper.cxx
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres.h
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres_tool.cc
  icaruscode/Decode/ChannelMapping/ChannelMapSQLite.cxx
  icaruscode/Decode/ChannelMapping/ChannelMapSQLite.h
  icaruscode/Decode/ChannelMapping/ChannelMapSQLite_tool.cc
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapDataTypes.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapPostGresProvider.cxx
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapPostGresProvider.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapPostGres_service.cc
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.tcc
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapSQLiteProvider.cxx
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapSQLiteProvider.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapSQLite_service.cc
  icaruscode/Decode/ChannelMapping/IChannelMapping.h
  icaruscode/Decode/ChannelMapping/IICARUSChannelMap.h
  icaruscode/Decode/ChannelMapping/IICARUSChannelMapProvider.h
  icaruscode/Decode/ChannelMapping/Legacy/CMakeLists.txt
  icaruscode/Decode/ChannelMapping/Legacy/ChannelMapPostGres_tool.cc
  icaruscode/Decode/ChannelMapping/Legacy/ChannelMapSQLite_tool.cc
  icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.cxx
  icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.h
  icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMap_service.cc
  icaruscode/Decode/ChannelMapping/PMTChannelMapDumper.cxx
  icaruscode/Decode/ChannelMapping/PositionFinder.h
  icaruscode/Decode/ChannelMapping/TPCChannelmapping.h
  icaruscode/Decode/ChannelMapping/channelmapping_icarus.fcl
  icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
  icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
  icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
  icaruscode/PMT/Calibration/PMTLaserCalibration_module.cc
  icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.cxx
Labels: enhancement, breaking

#720 Trigger decoder for adder triggers
  fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
  icaruscode/Decode/ChannelMapping/ChannelMapDumper.cxx
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx
  icaruscode/Decode/ChannelMapping/ChannelMapPostGres.h
  icaruscode/Decode/ChannelMapping/ChannelMapSQLite.cxx
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapDataTypes.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.h
  icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.tcc
  icaruscode/Decode/ChannelMapping/IChannelMapping.h
  icaruscode/Decode/ChannelMapping/IICARUSChannelMap.h
  icaruscode/Decode/ChannelMapping/IICARUSChannelMapProvider.h
  icaruscode/Decode/ChannelMapping/channelmapping_icarus.fcl
  icaruscode/Decode/DecoderTools/CMakeLists.txt
  icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
  icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.cxx
  icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
  icaruscode/TPC/Compression/producecompressedjob.fcl
  icaruscode/Utilities/CacheCounter.h
  icaruscode/Utilities/Expected.h
Labels: enhancement

#700 Workflow to enable ML File Production with refactored LArG4
  fcl/g4/larg4_icarus.fcl
  fcl/g4/larg4_icarus_intime.fcl
  fcl/g4/larg4_services_icarus.fcl
  fcl/g4/mergesimsources_icarus.fcl
  fcl/gen/corsika/prodcorsika_proton_intime_filter_bnb.fcl
Labels: enhancement, maintenance

#702 Workaround on FHiCL parameter set bug
  icaruscode/Utilities/ReadArtConfiguration.h
Labels: bug

#719 add data integrity filter to recompression fcl
  icaruscode/TPC/Compression/icarus_produce_compressed_job.fcl
Labels: enhancement

#721 Two updates: bug fix for keep up processing, adjust interplane time offsets and decon timing for truth matching
  fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
  fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_keepup.fcl
  icaruscode/Analysis/tools/TrackHitEfficiencyAnalysis_tool.cc
  icaruscode/Analysis/tools/analysis_tools_icarus.fcl
  icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
  icaruscode/TPC/ICARUSWireCell/icarus/sp.jsonnet
Labels: bug, enhancement

#713 fcl additions for stage1+larcv
  fcl/reco/Definitions/stage1_icarus_defs.fcl
  fcl/reco/Stage1/Run2/stage1_run2_1d_larcv_icarus_MPVMPR.fcl
  fcl/reco/Stage1/Run2/stage1_run2_1d_larcv_icarus_Nu.fcl
  fcl/reco/Stage1/Run2/stage1_run2_larcv_icarus_MPVMPR.fcl
  fcl/reco/Stage1/Run2/stage1_run2_larcv_icarus_Nu.fcl
Labels: enhancement
