Repository SBNSoftware/icaruscode, pull requests merged in 2024-05, with the labels that each got.

#736 Updates for Doxygen documentation generation
  doc/icaruscode.doxy
  doc/scripts/updateLocalDocumentation.sh
  doc/scripts/utilities.sh
Labels: maintenance

#735 sortDataLoggerFiles.py: fixed duplicate file identification
  scripts/sortDataLoggerFiles.py
Labels: bug

#673 Introduce fhicl to enable adjustment of the ICARUS simulation according to trigger emulation
  .gitignore
  fcl/caf/cafmaker_defs.fcl
  fcl/caf/cafmakerjob_icarus.fcl
  fcl/detsim/detsim_2d_icarus.fcl
  fcl/detsim/detsim_2d_icarus_refactored.fcl
  fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
  icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
  icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-shifted-refactored.jsonnet
  icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-shifted.jsonnet
Labels: enhancement
